### PR TITLE
More specific return type for tuple extractor

### PR DESCRIPTION
**Pull request by Billzabob**
See discussion here:
https://gitter.im/scala/scala?at=601b19b3428d9727dd52a156

### CODE REVIEW

**Comment by mpilquist** [comment]
CI build appears broken for unrelated reasons. Running `mimaReportBinaryIssues` locally results in the mima error I expected:

```scala
[info] Compiling 1 Scala source to /Users/mpilquist/Development/oss/scodec/testkit/jvm/target/scala-2.12/classes ...
[error]  * method unapply(scala.Tuple2)scala.Option in object scodec.codecs.package#~ has a different result type in current version, where it is scala.Some rather than scala.Option
[error]    filter with: ProblemFilters.exclude[IncompatibleResultTypeProblem]("scodec.codecs.package#~.unapply")
```

**Comment by mpilquist** [comment]
This might be fixable by restoring the original signature but making it `private[scodec]` (while leaving the new signature in place).

**Comment by martijnhoekstra** [comment]
Can't you put in a MiMa exception here? MiMa warns because the signature changed, but the returned runtime value is not changing and the underlying platform is never going to be able to observe the difference.

**Comment by mpilquist** [comment]
@martijnhoekstra Nope, it's truly binary incompatible.

```scala
➜  cat Foo.scala
object Foo {
  def unapply[A, B](t: (A, B)): Option[(A, B)] = Some(t)
}
➜  cat Bar.scala
object Bar extends App {
  (1, 2) match { case Foo(x, y) => println(x + y) }
}
➜  scalac Foo.scala Bar.scala
➜  scala -cp . Bar
3
```

Then we change the return type and only recompile Foo:

```scala
➜  cat Foo2.scala
object Foo {
  def unapply[A, B](t: (A, B)): Some[(A, B)] = Some(t)
}
➜  scalac Foo2.scala
➜  scala -cp . Bar
Exception in thread "main" java.lang.NoSuchMethodError: 'scala.Option Foo$.unapply(scala.Tuple2)'
	at Bar$.delayedEndpoint$Bar$1(Bar.scala:2)
	at Bar$delayedInit$body.apply(Bar.scala:1)
	at scala.Function0.apply$mcV$sp(Function0.scala:39)
	at scala.Function0.apply$mcV$sp$(Function0.scala:39)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:17)
	at scala.App.$anonfun$main$1(App.scala:76)
```

You can't use source compatibility rules to reason about binary compatibility.

**Pull request closed without merging**
